### ISSUE TITLE
Option for Low Temps

### ISSUE THREAD

**Issue by dbeltjr** [nigel-daniels/MMM-3Day-Forecast#11]
Would it be possible to incorporate options for a user to program for what data they would like to see? I really love the module, but have no need for Humidity, but a rather strong need for both High and Low temps. Or is there a simple way I can modify the code to replace humidity with Low? Thanks!

**Comment by nigel-daniels** [comment]
Hi, apologies for not responding sooner, a full time job has stopped me from being able to do much with these modules.  I'd recommend forking the code base and make the changes you need in a local repo.
