### ISSUE TITLE
french traduction

### ISSUE THREAD

**Issue by jerem1012** [nigel-daniels/MMM-3Day-Forecast#13]
hi Nigel and thanks a lot for your code

it help me a lot during my magic mirror project

you asked about translation in French language for différent section and I'm ready to help you on this topic if you want.

i installed you module on my magic mirror and as you told the section next day are ok for today and tomorrow but not for the third day which appear in Deutsch "overmorgen" with a pipe just before the word.

I can send you screen shot if needed.

For the translation of the third day I can suggest you "Après Demain"

please feel free to contact me for anything else

regards

jeremy

**Comment by H037** [comment]
I'm unable to make it work, maybe I miss something. 

J'accepterais volontier un coup de main francophone :)
:

**Comment by nigel-daniels** [comment]
@H037 Hi, most likely there is a problem in the config.js I recommend reviewing the config.js carefully, especially to check the quotes and commas used, problems with those can be hard to identify.
