### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by alebrug77** [nigel-daniels/MMM-3Day-Forecast#18]
How can I update this module?

**Comment by nigel-daniels** [comment]
You should be able to go into the module directory and run:

`git pull && npm install`

**Comment by alebrug77** [comment]
I'm getting this error
error: Your local charges to the following files would be overwritten by merge:
package-lock.json
Please commit your changes or stash them before you merge.
So I think git pull && npm install is the command to install the module instead of updating it. Or am I wrong?

**Comment by nigel-daniels** [comment]
Hi, this looks like a git error.  The bit about committing changes suggests something was altered in the directory.  I’d check the git docs to either override the changes or back them out first.

**Comment by jacobmealey** [comment]
if you only changed package-lock can't you just run `git reset --hard HEAD`? then you should be able to run `git pull && npm install`  this does beg the question, should package-lock.json to the .gitignore? is that good practice?

**Comment by ppatrickxctw** [comment]
Hi, I have a translation for lang zh-tw.
"Day after" as "後天"

**Comment by nigel-daniels** [comment]
@ppatrickxctw thanks for the suggestion, if you make a pull request I'll add the translation file.
