### ISSUE TITLE
Black Screen after MM 2.13.00 Update

### ISSUE THREAD

**Issue by M1dn8** [nigel-daniels/MMM-3Day-Forecast#19]
Good Evening from Germany :)

After I updated to the new MagicMirror version 2.13.00, the Mirror show a black screen!
I tried turning off every module and stopped at the MMM-3Day-Forecast module. Without this module in my config the MM is starting as it should! So pls could u check what's the problem with the MM Update and this module is?!

Thank u for your work :) 

best regards

**Comment by clone2324** [comment]
I think I figured out the issue. Please update the module and try again!

**Comment by M1dn8** [comment]
PERFECT :)
Thank you for this fast solution!!!
Now my Mirror works again with the 3Day Forcast module...thank u very much!
