### ISSUE TITLE
Undefined weather and broken pictures

### ISSUE THREAD

**Issue by BassXX** [nigel-daniels/MMM-3Day-Forecast#31]
Hi, since the move to the new API, I get some problems with the weather view. See screenshot

![mirror](https://user-images.githubusercontent.com/17762990/196646330-d7126ff2-e729-47fb-8621-ea3092888344.png)

**Comment by nigel-daniels** [comment]
@BassXX thanks for logging this, I was able to recreate the issue and I hope it is now fixed. I was basing tomorrow and the next days conditions on exactly noon, I've made this a range to better suite various time zones. If this works for you please close the issue as fixed.

**Comment by BassXX** [comment]
Yes - its fixed for me now! Thank you!
