### ISSUE TITLE
Reduce decimal places?

### ISSUE THREAD

**Issue by BassXX** [nigel-daniels/MMM-3Day-Forecast#32]
Hello again :)

Not really an issue, more a suggestion/request.

Since the new API, Temperature, Rain Probability, etc. is now displayed with 2 decimal places (XX.YY).

I personally do not need it to be that precise, also it takes away some space. For me it would be perfectly fine to reduce it to one decimal place (XX.Y) or to remove the fraction at all.

Maybe it could be possible to create a config parameter, where the users can decide for themself whether they want fractions to be displayed? Or how many decimal places they want to be displayed?

**Comment by nigel-daniels** [comment]
@BassXX I've rounded everything to whole numbers, after all the concept for this was you can glance in the mirror and get an idea of what's coming and what it's like today. I also added the rounding to the MMM-Weather-Now module. BTW I also fixed a bug with the timezones. You may not have seen it close to UTC/GMT but some of the future days weather was not in sync with the local TZ. It was more noticeable in further out TZs like Pacific where some night icons were appearing.

**Comment by BassXX** [comment]
Perfect! Everything seems to work great! Thanks a lot :)
