### ISSUE TITLE
Thanks for your work with this. How do I update it? 

### ISSUE THREAD

**Issue by bclinton1** [nigel-daniels/MMM-3Day-Forecast#33]
I am behind 8 commits from the master branch. I followed the instructions for installing it but it still show behind and I am not getting updates after I changed the API key to open weather.

**Comment by bclinton1** [comment]
Update - I ran git pull and updated the module but I can't get past loading....on the MM display. It seems to be stuck at that point.

**Comment by bclinton1** [comment]
Update 2......I shut down MM and brought it back up and all seems to be fine with the module now. Thank you again for your hard work with this.....it's a great module!

**Comment by nigel-daniels** [comment]
I'm glad it is finally working for you! Looks like the good old IT Crowd 'Turn it off and back on again.' worked :) Any other problems please just raise an issue and I'll try and help out.
