### ISSUE TITLE
Is the module still working?

### ISSUE THREAD

**Issue by bclinton1** [nigel-daniels/MMM-3Day-Forecast#40]
Hi friends. The module has worked fine in the past but now I get "Loading..." and that's it. I have reinstalled the module. Here is my config

{
    		module:     'MMM-3Day-Forecast',
		disabled: false,
    		position:   'bottom_center',
		config: {
		api_key:    'XXXXXXXXXXXX',
		lat:        34.756060,
		lon:        -92.267770,
		units:      'I',
		lang:       'en',
		interval:   900000
		}
		},

**Comment by nigel-daniels** [comment]
Hi, the module still works, and as far as I can tell the config looks good. BTW it now needs to use a key for the OpenWeather API not the old Bit weather API.

**Comment by bclinton1** [comment]
I was using a WU key...just went in and generated another one and still stuck on loading.... thanks for the reply though....

**Comment by nigel-daniels** [comment]
A WU key will no longer work, you need to generate and OpenWeather API key, as per the updated docs. Sadly WU and BitWeather went to pay for models with no effective free tier.

**Comment by bclinton1** [comment]
It is OW key...

    On Wednesday, March 15, 2023 at 03:24:25 PM CDT, Nigel Daniels ***@***.***> wrote:  
 
 


A WU key will no longer work, you need to generate and OpenWeather API key, as per the updated docs. Sadly WU and BitWeather went to pay for models with no effective free tier.

**Comment by nigel-daniels** [comment]
I cannot see any reason for this not to show. Afaik the config except above looks ok, is it possible to share the full redacted config to test?

**Comment by bclinton1** [comment]
[config.zip](https://github.com/nigel-daniels/MMM-3Day-Forecast/files/10984472/config.zip)


Thanks for helping.

**Comment by nigel-daniels** [comment]
The config looks good so I just ran up a test of the module based on the file you sent to me and got the following:
 
![screen](https://user-images.githubusercontent.com/4641452/225453581-73c4d16e-77b6-46ab-80df-318971993035.png)

I took the config for the MMM-3Day-Forecast you sent and used it in a simplified test config:

```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
	address: "0.0.0.0",
	port: 8080,
        ipWhitelist: [],
	language: 'en',
	timeFormat: 24,
	units: 'metric',

	modules: [
		{
			module: 'alert',
		},
		{
			module: 	'clock',
			position: 	'top_left'
		},
		{
    		module:     'MMM-3Day-Forecast',
			disabled: false,
    		        position:   'bottom_center',
			config: {
			    api_key:    'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
			    lat:        34.756060,
			    lon:        -92.267770,
			    units:      'I',
			    lang:       'en',
			    interval:   900000
			}
		}
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;} 
```

this makes me suspect that. something else in your config is causing an issue, I recommend simplifying the config to something like the above and see if this module is ok. If it is add each module back in one by one until you can id the culprit. If it does not work in a simple config like the above then I suspect a network issue is at fault.

**Comment by bclinton1** [comment]
Ok, looks like I got something else going on then. I appreciate you helping.
    On Wednesday, March 15, 2023 at 05:09:51 PM CDT, Nigel Daniels ***@***.***> wrote:  
 
 


The config looks good so I just ran up a test of the module based on the file you sent to me and got the following:



I took the config for the MMM-3Day-Forecast you sent and used it in a simplified test config:
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
	address: "0.0.0.0",
	port: 8080,
        ipWhitelist: [],
	language: 'en',
	timeFormat: 24,
	units: 'metric',

	modules: [
		{
			module: 'alert',
		},
		{
			module: 	'clock',
			position: 	'top_left'
		},
		{
    		module:     'MMM-3Day-Forecast',
			disabled: false,
    		        position:   'bottom_center',
			config: {
			    api_key:    'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
			    lat:        34.756060,
			    lon:        -92.267770,
			    units:      'I',
			    lang:       'en',
			    interval:   900000
			}
		}
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;} 

this makes me suspect that. something else in your config is causing an issue, I recommend simplifying the config to something like the above and see if this module is ok. If it is add each module back in one by one until you can id the culprit. If it does not work in a simple config like the above then I suspect a network issue is at fault.

**Comment by bclinton1** [comment]
> [config.zip](https://github.com/nigel-daniels/MMM-3Day-Forecast/files/10984472/config.zip)
> 
> Thanks for helping.

Using just your config I still get loading......I even created another account on OW and tried a new API key. Definitely weird....The other modules I am using run fine. I'll keep digging. Thanks again.

**Comment by nigel-daniels** [comment]
The API request for this is:
```
https://api.openweathermap.org/data/2.5/forecast?appid=xxxxxxxxxxxxxxxxxxxxxxxxxx&lat=34.756060&lon=-92.267770&units=I&lang=en&cnt=24
````

If you try this in your browser you should see a result that starts out something like:

```
{"cod":"200","message":0,"cnt":24,"list":[{"dt":1678924800,"main":{"temp":286.4,"feels_like":284.98,"temp_min":283.68,"temp_max":286.4,"pressure":1022,"sea_level":1022,"grnd_level":...
```

There should be several rows of this response! The important part is the opening "cod"=200 that indicates all went well.

**Comment by bclinton1** [comment]
Holy Cow! Everything works now! I started with the config you sent me in email as you suggested and used my original API key and it works! Thank you so much!
    On Wednesday, March 15, 2023 at 05:58:30 PM CDT, Nigel Daniels ***@***.***> wrote:  
 
 


The API request for this is:
https://api.openweathermap.org/data/2.5/forecast?appid=xxxxxxxxxxxxxxxxxxxxxxxxxx&lat=34.756060&lon=-92.267770&units=I&lang=en&cnt=24

If you try this in your browser you should see a result that starts out something like:
{"cod":"200","message":0,"cnt":24,"list":[{"dt":1678924800,"main":{"temp":286.4,"feels_like":284.98,"temp_min":283.68,"temp_max":286.4,"pressure":1022,"sea_level":1022,"grnd_level":...

There should be several rows of this response! The important part is the opening "cod"=200 that indicates all went well.

**Comment by nigel-daniels** [comment]
Great, I guess then something else is blocking it the the original config file? Maybe just try with your original config file with all other modules commented out hopefully all is well. If not there is a global setting causing a problem. If it works then comment in each module one by one until the cause of the bad interaction is found. Maybe we can figure out what the root cause is at that point!

**Comment by bclinton1** [comment]
Can I ask? It is warning me that I need to update the module? What is the correct procedure? I certainly don't want to break it :)
    On Wednesday, March 15, 2023 at 07:02:27 PM CDT, Nigel Daniels ***@***.***> wrote:  
 
 


Great, I guess then something else is blocking it the the original config file? Maybe just try with your original config file with all other modules commented out hopefully all is well. If not there is a global setting causing a problem. If it works then comment in each module one by one until the cause of the bad interaction is found. Maybe we can figure out what the root cause is at that point!

**Comment by nigel-daniels** [comment]
By the sounds of it the module is up to date and you just demonstrated it's working. However in the original `config.js` something is causing it not to load correctly. 

My previous recommendation is to go into the `modules: [...]` list and comment out all of the other modules except MMM-3Day-Forecast and verify it runs ok. If it does not there is something in the rest of the config causing an issue. 

If it works ok, then comment out everything except MMM-3Day-Forecast and one other module. See if they work together ok. If all is good continue adding in modules one at a time until something breaks. Then we know there is some interaction between those modules that's causing a problem. 

I hope that makes sense?

**Comment by bclinton1** [comment]
Ok, thanks for taking the time to help me.
    On Wednesday, March 15, 2023 at 07:21:44 PM CDT, Nigel Daniels ***@***.***> wrote:  
 
 


By the sounds of it the module is up to date and you just demonstrated it's working. However in the original config.js something is causing it not to load correctly.

My previous recommendation is to go into the modules: [...] list and comment out all of the other modules except MMM-3Day-Forecast and verify it runs ok. If it does not there is something in the rest of the config causing an issue.

If it works ok, then comment out everything except MMM-3Day-Forecast and one other module. See if they work together ok. If all is good continue adding in modules one at a time until something breaks. Then we know there is some interaction between those modules that's causing a problem.

I hope that makes sense?

**Comment by nigel-daniels** [comment]
Np. I want to verify the module does not have a bug that needs checking out :)
