### ISSUE TITLE
Weather Data Show NaN

### ISSUE THREAD

**Issue by cweinhofer** [nigel-daniels/MMM-3Day-Forecast#43]
I just upgraded to the most recent commit and now my weather data shows like this:
![Screenshot 2024-05-03 142343](https://github.com/nigel-daniels/MMM-3Day-Forecast/assets/7067427/2585e891-6485-4f84-ab56-399e37a6c436)

I went in to OpenWeather and everything looks good on my account. I even set up a new key to make sure it was good with the new 3.0 system, but no difference.

Any idea what's going on? My config is below if you need (each X stands in for one character).

```
		{
			module:     "MMM-3Day-Forecast",
			position:   "top_center",
			config: {
				api_key:    "XXXXXXXXX481d367abe3224cae79edd2",
				lat:        XX.xx9845,
				lon:        -XX.xx9502,
				interval:   3600000,
				horizontalView: true,
			}
		},
```

**Comment by nigel-daniels** [comment]
Hi, thanks for the report, let me investigate, I accepted the upgrade to 3.0 commit and assumed it was tested out, I'll check into this, probably one the weekend.

**Comment by nigel-daniels** [comment]
On investigation the pull request I recently received proved not to have been tested. It turns out the OpenWeather API is going to change and will now require credit card details as well as a more extensive rewrite. For now I'm rolling back to the V2.5 API but I'm planning to rebase on Weather.API.

**Comment by cweinhofer** [comment]
Thanks. Back to working.

**Comment by nigel-daniels** [comment]
@cweinhofer FYI, I just updated this module and MMM-Weather-Now to use [WeatherAPI](https://www.weatherapi.com). If you update the `api_key` in the config and do a `pull` in the directory, then restart the mirror this should be on the new API.
