### ISSUE TITLE
F for Horizontal View

### ISSUE THREAD

**Issue by husoseli15** [nigel-daniels/MMM-3Day-Forecast#5]
module:     'MMM-3Day-Forecast',
                        position:   'top_right',
                        config: {
                                api_key:    'XXXX',
                                lat:        XXX,
                                lon:        XXXX,
                                units:      'I',
                                lang:       'en',
                                horizontalView: true,
                                interval:   900000
               
I can't get fahrenheit (imperial) in horizontal view. Am I doing something wrong? 

Thank you.

**Comment by nigel-daniels** [comment]
@husoseli15 thanks for raising this issue, there was a defect where I was assigning the units back to M by mistake.  That's fixed now so do a `git pull` in the `MMM-3Day-Forecast` module directory and restart.  You should now see values in Imperial measures.

**Comment by husoseli15** [comment]
@nigel-daniels it's fixed. Thanks a lot!
