### ISSUE TITLE
transparent graphics

### ISSUE THREAD

**Issue by cweinhofer** [nigel-daniels/MMM-3Day-Forecast#6]
Is there a reason why the graphics all include a background (i.e. not transparent)? This makes the module look really bad when placed over top of a background element.

I'd be happy to help convert them, if I can get copies of the source graphics.

**Comment by nigel-daniels** [comment]
The graphics assume a black background but if you want to convert the black to a transparent then please just do a pull request. All of the graphics used are in the repo.

**Comment by cweinhofer** [comment]
I'm not sure what kind of source files you have for the graphics, but I was thinking that converting using the source would produce a cleaner end result than simply editing the rasterized graphics. Any way I could get access to those?

**Comment by nigel-daniels** [comment]
I'm afraid I did not create these from any source files as such (eg. Photoshop, Illustrator or similar).  I hacked these around in Photoshop Elements from parts I found on-line, so I guess they are kind of Frakengraphics.  Sadly I didn't keep any of that stuff once I had the files I needed for the module.

**Comment by cweinhofer** [comment]
In that case, I think the "Color to Alpha" tool in GIMP will probably be the best bet. I'll update once I've had a chance to work on them.

**Comment by cweinhofer** [comment]
I was doing some stuff with another module and I came across these: https://github.com/erikflowers/weather-icons What do you think about using these -- especially given that they are already included in MM's vendor node modules?

Would it be possibly to call these up automatically as a font  / CSS? (Sorry, if that's a dumb question. I know very little about coding.) If not, but you are still open to using them, I can see about converting the SVG's to either PNG or GIF.

**Comment by nigel-daniels** [comment]
That looks like a great symbol font set, I wish I'd known about them some time ago.  Unfortunately using these would take some code effort to start calling some kind of look up to pull the right one.  Currently I don't have as much time as I started a new job.  If you have the time the simplest would be to fork this repo, turn the current black backgrounds transparent then make a pull request to update.

**Comment by yohaybn** [comment]
I just change it to weather-icons.
please see my pull request
